
const global ={
welcomeText_en:"The International Performance Hub (IPH) is designed to track Saudi Arabia’s performance in relevant indicators against more than 200 countries around the world. IPH provides an overview of the Kingdom’s standing in over 250 international indicators accross 12 main pillars. It is also a reference for international rankings, as it makes it possible to find out how different countries tally across multiple areas of activity, from industry and commerce to social affairs, and monitor progress periodically.",
startText_en:"Click start to begin tracking performance.",
welcomeText_ar:"صممت منصة المقارنات الدولية لمتابعة أداء المملكة العربية السعودية مقارنةً  بـأكثر من 200 دولة أخرى حول العالم، حيث تظهر المنصة نظرة شاملة عن أدء المملكة في أكثر من 250 مؤشر قياسي عالمي عبر 12 محور قياس. كما تمثل المنصة مرجعاُ للتصنيفات الدولية  حيث أنها تمكن من إجراء مقارنات خاصة بأداء الدول المختلفة في عدة مجالات من الصناعة والتجارة إلى الشؤون الاجتماعية و مراقبة الأداء بشكل دوري.",
startText_ar:"اضغط زرابدأ لمتابعة الأداء",
startbtn_en_wel:"START",
startbtn_ar_wel:"ابدأ",
iph_text_line1_en:"Welcome to the",
iph_text_line2_en:"International Performance Hub",
iph_text_line1_ar:"مرحباً بكم في منصة",
iph_text_line2_ar:"المقارنات الدولية",
comparePanel_title_en:"Compare",
comparePanel_title_ar:"قارن",
fullstatsBtn_en:"Full Data for ",
fullstatsBtn_ar:"بيانات كاملة لـ",
generateGraphicsBtn_en:"GENERATE GRAPHS",
generateGraphicsBtn_ar:"إنشاء رسم بياني",
nodata_compare_en:"no data",
nodata_compare_ar:"لا توجد بيانات",
pillar_decr_en:"Select a pillar to see relevant country data and map visualization",
pillar_decr_ar:"اختر أحد المحاور لعرض البيانات ذات الصلة على خارطة الدول",
subPillars_en:"Sub Pillars",
subPillars_ar:"المحاور الثانوية",
pillar_en:"Pillars",
pillar_ar:"المحاور",
statsTitlePart1_en:"Full Data for ",
statsTitlePart1_ar:"بيانات كاملة لـ ",
rankingTableCountriesText_en:"COUNTRIES",
rankingTablerankText_en : "RANK",
rankingTablescoreText_en : "SCORE",
rankingTableCountriesText_ar:"دول",
rankingTablerankText_ar : "المقارنة",
rankingTablescoreText_ar : "النتيجه",
KpiText_en:"KPI",
KpiText_ar:"مؤشر قياس",
CountryLimit:20,
Addcountries:'Add countries',
Benchmarks:'Benchmarks',
Datasource:'Data source',
GraphTitleStatic:'Figures for',
placeHolder:'Select Countries',
benchMarkWorld:'World',
benchMarkG20:'G20',
benchMarkGCC:'GCC',
benchMarkArab:'Arab World',
benchMarkOECD:'OECD',
DatasourceYearStatic:'Year',
Frequency:'Frequency',
benchMarkDescription:'Description',    
Addcountries_ar: 'إضافة دول ',
Benchmarks_ar:'القيم المرجعية',
Datasource_ar:'مصدر ',
GraphTitleStatic_ar:'أرقام  لـ', 
placeHolder_ar:'اختر دول', 
benchMarkWorld_ar:'عالم',
benchMarkG20_ar:'مجموعة العشرين',
benchMarkGCC_ar:'دول مجلس التعاون الخليجي',
benchMarkArab_ar:'الوطن العربي',
benchMarkOECD_ar:'منظمة التعاون الاقتصادي والتنمية',
DatasourceYearStatic_ar: 'سنة',
Frequency_ar:'التردد',
benchMarkDescription_ar:'الوصف', 
LanguageBtn_en:'English',
LanguageBtn_ar:'عربى',
AboutBtn_en:'About',
AboutBtn_ar:'عن المنصة',
AboutDescription_en:'The International Performance Hub (IPH) is designed to track Saudi Arabia’s performance in relevant indicators against 150 countries around the world. Developed from over 300 global indicators and with over 2,000 KPIs across 12 pillars of measurement, the International Performance Hub will provide an overview of the Kingdom’s standing from a big picture level. It is also a reference for international rankings, as it makes it possible to find out how different countries tally across multiple areas of activity, from industry and commerce to social affairs, and monitor progress periodically.',
AboutDescription_ar:'صممت منصة المقارنات الدولية لمتابعة أداء المملكة العربية السعودية مقارنةً  بـ 150 دولة أخرى حول العالم، حيث تم تطوير المنصة ضمن 300 مؤشر قياس دولي وأكثر من 2000 مؤشر قياس أداء رئيسي عبر 12 محور قياس. منصة المقارنات الدولية تتيح الفرصة  للحصول على نظرة شاملة عن أداء المملكة، كما تمثل المنصة مرجعاُ للمؤشرات الدولية، تمكَن الجهات المهتمة والمختصين في أنحاء العالم من إجراء مقارنات خاصة بالأداء دول مختلفة في عدة مجالات من الصناعة والتجارة إلى الشؤون الاجتماعية وبشكل دوري.',
Home_en:'Home',
Home_ar:'Home',
ShowKPISectionText_en:'SHOW ALL SUBPILLARS FOR',
ShowKPISectionText_ar:'SHOW ALL SUBPILLARS FOR',
HideKPISectionText_en:'HIDE ALL SUBPILLARS FOR',
HideKPISectionText_ar:'HIDE ALL SUBPILLARS FOR',
CountryDetailsTitle_en:'Country details',
CountryDetailsTitle_ar:'Country details',
ShowDataSourceText_en:'SHOW DATASOURCE',
ShowDataSourceText_ar:'SHOW DATASOURCE',
HideDataSourceText_en:'HIDE DATASOURCE',
HideDataSourceText_ar:'HIDE DATASOURCE',



}

module.exports = global;